### ISSUE TITLE
LoadError due to adressable

### ISSUE THREAD

**Issue by tbu** [MeisterLabs/atlassian-jwt-authentication#8] opened 2016-09-21 19:34 UTC
Hi,
Trying to start my rails server I now receive the following load error:
@rails500/bundler/gems/atlassian-jwt-authentication-32974f1d891f/lib/atlassian-jwt-authentication/helper.rb:3:in `require': cannot load such file -- addressable (LoadError)

Any idea?

**Comment by bulinutza** [comment] 2016-09-22 10:37
Hi tbu,

Thanks for reporting this, it was caused by a missing dependency introduced by a pull request. I have updated the dependency list now, so please uninstall the gem and then install it again to get the new version. It should be fixed.

**Comment by tbu** [comment] 2016-09-22 11:45
Thanks Laura, 

Rails server is up and running, but using rest_api_call fails:
_undefined method `get' for AtlassianJwtAuthentication::HTTParty:Module

**Comment by bulinutza** [comment] 2016-09-22 13:27
Fixed as well, please do the same as above.

**Comment by tbu** [comment] 2016-09-22 14:03
Thanks. Works.

**Closed as completed** 2016-09-22 14:09 UTC
